apiVersion: v1
kind: Service
metadata:
  name: modsec-frontend
  namespace: security
  labels:
    app: modsec
spec:
  selector:
    app: modsec
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: Service
meta
  name: modsec-controller-svc
  namespace: security
  labels:
    app: controller
spec:
  selector:
    app: modsec
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: api
  type: ClusterIP